name: Branch Build

on:
  workflow_call:
    inputs:
      BRANCH:
        description: Git branch to fetch code from
        required: true
        default: main
        type: string

env:
  NODE_VERSION: 14.21.3

jobs:
  branch-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.BRANCH }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: |
          #echo "::set-output name=dir::$(yarn cache dir)"
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT


      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: Run modules
        uses: borales/actions-yarn@v5
        with:
          cmd: modules # will run `yarn modules` command

      - name: Run build
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/webpack
