name: Branch Build

#on:
#  push:
#    branches:
#    - master
#    - release-*

on:
  workflow_call:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker
  NODE_VERSION: 12.16.0

permissions:
  contents: read

jobs:
  branch-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: | 
          #echo "::set-output name=dir::$(yarn cache dir)"
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT


      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Prepare build variables
        id: build_variables
        run: |
          echo "VERSION=$(git describe --tags --abbrev=0 --match="v[0-9]*" | cut -c2-)-dev-${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT


      - name: Build
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.build_variables.outputs.VERSION }}
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/webpack
