name: "Build Docker image for Deck"

on:
    workflow_call:

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Add executable permissions
        working-directory: ${{ github.workspace }}
        run: |
          #ls -lth /home/runner/work/deck/deck
          ls -lht /home/runner/work/deck/deck/build
          #mkdir -p build/webpack
          #mv /home/runner/work/deck/deck/* build/webpack/
          #chmod +x deck

      - name: Set release info
        run: |
          event_type=${{ github.event.action }}
          # release_version=$(echo ${{ github.ref_name }} | sed 's/v//g' | sed 's/+/-/g')
          release_version="0.0.0"
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          if [[ $event_type == "released" ]]; then
            echo "TAGS=${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:$release_version,${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
          else
            echo "TAGS=${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:$release_version" >> $GITHUB_ENV
          fi

      - name: Print release info
        run: |
            echo "$GITHUB_ENV.RELEASE_VERSION"
            echo "GITHUB_ENV.TAGS"

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker context for buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
          driver-opts: |
            image=moby/buildkit:master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: "./Dockerfile.ubuntu"
          tags: ${{ env.TAGS }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_NAME }}
      #      org.opencontainers.image.version=${{ env.RELEASE_VERSION }}