name: Build Docker image for Deck and push it to GitHub Container Registry

on:
  workflow_call:
    inputs:
      IMAGE_VERSION:
        description: Version to use for image tag
        required: true
        default: "0.0.0"
        type: string
      BRANCH:
        description: Git branch to fetch code from
        required: true
        default: main
        type: string

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/thd-${{ github.event.repository.name }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.BRANCH }}

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build/webpack

      - name: Set release info
        run: |
          release_version=${{ inputs.IMAGE_VERSION }}
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          echo "TAGS=${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:$release_version" >> $GITHUB_ENV

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker context for buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
          driver-opts: |
            image=moby/buildkit:master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: "./Dockerfile.ubuntu"
          platforms: linux/amd64
          tags: ${{ env.TAGS }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ env.RELEASE_VERSION }}
