name: Release

on:
    workflow_dispatch:
        inputs:
            BRANCH:
                description: 'Git branch to fetch code from'
                required: true
                default: 'master'
                type: string
            THD_DECK_VERSION:
                description: 'Version of THD Deck'
                required: true
                default: "0.0.0"
                type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
        BRANCH: ${{ inputs.BRANCH }}

  docker:
    needs: build
    uses: ./.github/workflows/docker-build.yml
    with:
        BRANCH: ${{ inputs.BRANCH }}
        IMAGE_VERSION: ${{ inputs.THD_DECK_VERSION }}