name: Release

permissions:
  contents: write
  packages: write
  actions: read

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Git branch to fetch code from
        required: true
        default: main
        type: string
      IMAGE_VERSION:
        description: Version to use for image tag
        required: true
        default: dev
        type: string

env:
  NODE_VERSION: 14.21.3
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/thd-${{ github.event.repository.name }}

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check if image tag already exists in ghcr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION="${{ inputs.IMAGE_VERSION }}"

          if [[ "$RELEASE_VERSION" != "0.0.0" && "$RELEASE_VERSION" != "dev" ]]; then
            echo "Checking if tag '$RELEASE_VERSION' exists in GHCR..."

            EXIST=$(gh api "/orgs/homedepot/packages/container/thd-${{ github.event.repository.name }}/versions" --jq \
              ".[] | select(.metadata.container.tags[]? == \"$RELEASE_VERSION\") | .id" || true)

            if [[ -n "$EXIST" ]]; then
              echo "Error: Image tag '$RELEASE_VERSION' already exists in GHCR."
              exit 1
            else
              echo "Tag '$RELEASE_VERSION' does not exist. Proceeding."
            fi
          else
            echo "Skipping tag check for version '$RELEASE_VERSION'"
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: validate-version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.BRANCH }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
<<<<<<< HEAD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

=======
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
>>>>>>> remotes/upstream/release-1.33.x
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

<<<<<<< HEAD
      - uses: actions/cache@v4
=======
      - uses: actions/cache@v3
>>>>>>> remotes/upstream/release-1.33.x
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
<<<<<<< HEAD

      - name: Build
        run: ./gradlew --info build

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
=======
      - name: Assemble release info
        id: release_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . .github/workflows/release_info.sh ${{ github.event.repository.full_name }}
          echo CHANGELOG=$(echo -e "${CHANGELOG}") >> $GITHUB_OUTPUT
          echo SKIP_RELEASE=${SKIP_RELEASE} >> $GITHUB_OUTPUT
          echo IS_CANDIDATE=${IS_CANDIDATE} >> $GITHUB_OUTPUT
          echo RELEASE_VERSION=${RELEASE_VERSION} >> $GITHUB_OUTPUT
      - name: Prepare build variables
        id: build_variables
        run: |
          echo REPO=${GITHUB_REPOSITORY##*/} >> $GITHUB_OUTPUT
          echo VERSION="$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Release build
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.release_info.outputs.RELEASE_VERSION }}
          ORG_GRADLE_PROJECT_nexusPublishEnabled: true
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_nexusPgpSigningKey: ${{ secrets.NEXUS_PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_nexusPgpSigningPassword: ${{ secrets.NEXUS_PGP_SIGNING_PASSWORD }}
        run: |
          ./gradlew --info build
      - name: Publish apt packages to Google Artifact Registry
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.release_info.outputs.RELEASE_VERSION }}
          ORG_GRADLE_PROJECT_artifactRegistryPublishEnabled: true
          GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
        run: |
          ./gradlew --info publishDebToArtifactRegistry
      - name: Login to Google Cloud
        # Only run this on repositories in the 'spinnaker' org, not on forks.
        if: startsWith(github.repository, 'spinnaker/')
        uses: 'google-github-actions/auth@v2'
        # use service account flow defined at: https://github.com/google-github-actions/upload-cloud-storage#authenticating-via-service-account-key-json
        with:
          credentials_json: '${{ secrets.GAR_JSON_KEY }}'
      - name: Upload halconfig profiles to GCS
        # https://console.cloud.google.com/storage/browser/halconfig
        # Only run this on repositories in the 'spinnaker' org, not on forks.
        if: startsWith(github.repository, 'spinnaker/')
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'halconfig/'
          destination: 'halconfig/${{ steps.build_variables.outputs.REPO }}/${{ steps.release_info.outputs.RELEASE_VERSION }}'
          parent: false
      - name: Login to GAR
        # Only run this on repositories in the 'spinnaker' org, not on forks.
        if: startsWith(github.repository, 'spinnaker/')
        uses: docker/login-action@v3
        # use service account flow defined at: https://github.com/docker/login-action#service-account-based-authentication-1
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Build and publish slim container image
        # Only run this on repositories in the 'spinnaker' org, not on forks.
        if: startsWith(github.repository, 'spinnaker/')
>>>>>>> remotes/upstream/release-1.33.x
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
<<<<<<< HEAD
          file: ./Dockerfile.ubuntu
          platforms: linux/amd64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_VERSION }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ inputs.IMAGE_VERSION }}

      - name: Create GitHub release
        if: ${{ inputs.IMAGE_VERSION != '0.0.0' && inputs.IMAGE_VERSION != 'dev' }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.IMAGE_VERSION }}
          tag_name: ${{ inputs.IMAGE_VERSION }}
          draft: false
          prerelease: false
=======
          tags: |
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.release_info.outputs.RELEASE_VERSION }}-unvalidated"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.release_info.outputs.RELEASE_VERSION }}-unvalidated-slim"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.release_info.outputs.RELEASE_VERSION }}-${{ steps.build_variables.outputs.VERSION }}-unvalidated-slim"
      - name: Build and publish ubuntu container image
        # Only run this on repositories in the 'spinnaker' org, not on forks.
        if: startsWith(github.repository, 'spinnaker/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.release_info.outputs.RELEASE_VERSION }}-unvalidated-ubuntu"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.release_info.outputs.RELEASE_VERSION }}-${{ steps.build_variables.outputs.VERSION }}-unvalidated-ubuntu"
      - name: Create release
        if: steps.release_info.outputs.SKIP_RELEASE == 'false'
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.release_info.outputs.CHANGELOG }}
          draft: false
          name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          prerelease: ${{ steps.release_info.outputs.IS_CANDIDATE }}
          tag_name: ${{ github.ref }}
>>>>>>> remotes/upstream/release-1.33.x
          token: ${{ secrets.GITHUB_TOKEN }}
