name: Release

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Git branch to fetch code from
        required: true
        default: main
        type: string
      THD_DECK_VERSION:
        description: Version of THD Deck
        required: true
        default: "0.0.0"
        type: string

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Validate THD_DECK_VERSION value
        id: check_special
        run: |
          if [[ "${{ inputs.THD_DECK_VERSION }}" == "0.0.0" || "${{ inputs.THD_DECK_VERSION }}" == "dev" ]]; then
            echo "special=true" >> $GITHUB_OUTPUT
          else
            echo "special=false" >> $GITHUB_OUTPUT
          fi

      - name: Fetch existing tags and releases
        if: steps.check_special.outputs.special == 'false'
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin refs/tags/${{ inputs.THD_DECK_VERSION }} | wc -l)
          RELEASE_EXISTS=$(gh release view ${{ inputs.THD_DECK_VERSION }} > /dev/null 2>&1 && echo 1 || echo 0)

          if [[ "$TAG_EXISTS" -gt 0 || "$RELEASE_EXISTS" -gt 0 ]]; then
            echo "Error: Version '${{ inputs.THD_DECK_VERSION }}' already exists as a tag or release."
            exit 1
          fi

  build:
    needs: validate-version
    uses: ./.github/workflows/build.yml
    with:
      BRANCH: ${{ inputs.BRANCH }}

  docker:
    needs: build
    uses: ./.github/workflows/docker-build.yml
    with:
      BRANCH: ${{ inputs.BRANCH }}
      IMAGE_VERSION: ${{ inputs.THD_DECK_VERSION }}
